# 
# ### Packages ###
# 
# install.packages("dplyr")
# install.packages("phyloseq2")
# install.packages("tidyr")
# install.packages("ggplot2")
# install.packages("devtools")
# install.packages("dada2"); packageVersion("dada2")
# install.packages("Biostrings")
# install.packages("ape")
# install.packages("BiocManager")
# install.packages("Hmisc")
# install.packages("yaml")
# install.packages("utils")
# install.packages("stats")
# install.packages("readr")
# install.packages("vegan")
# install.packages("dendextend")
# install.packages("viridis")
# install.packages("reshape")
# install.packages("DESeq2")
# install.packages("scales")
# install.packages("wesanderson")
# install.packages("ggpubr")
# install.packages("ips")
# install.packages("seqinr")
# install.packages("pheatmap")
# install.packages("remotes")
# install.packages("Formula")
# install.packages("gridExtra")
# install.packages("pals")
#install.packages("DAtest")
# install.packages("network")
# install.packages('igraph')
# install.packages('tidygraph')
# install.packages('ggraph')
# install.packages('RCy3')
# install.packages('ANCOMBC')
# install.packages('microbiome')
#install_github("microbiome/microbiome")
# install.packages('GGally')
# install.packages('rstatix')
# install.packages('kableExtra')
# install.packages('RColorBrewer')
# install.packages('NetCoMi')
# install_github("aametwally/MetaLonDA", ref = "master")
#install.packages("Polychrome")
#install.packages("lsmeans")
#install.packages("venn")
#BiocManager::install("ComplexHeatmap")
#devtools::install_github("jokergoo/circlize")
#remotes::install_github("wilkelab/gridtext")


### Packages ###

library("dplyr")
library("multcomp")
library("phyloseq2")
library("tidyr")
library("ggplot2")
library("devtools")
library("dada2"); packageVersion("dada2")
library("Biostrings")
library("ape")
library("BiocManager")
library("Hmisc")
library("yaml")
library("utils")
library("stats")
library("readr")
library("vegan")
library("dendextend")
library("viridis")
library("reshape")
library("scales")
library("wesanderson")
library("pheatmap")
library("ggpubr")
library("ips")
library("seqinr")
library("pheatmap")
library("remotes")
library("Formula")
library("gridExtra")
library("pals")
library("DAtest")
library("network")
library('igraph')
library('tidygraph')
library('ggraph')
library('RCy3')
library('ANCOMBC')
library('microbiome')
library('GGally')
library('rstatix')
library('kableExtra')
library('RColorBrewer')
library('NetCoMi')
library("readxl")
library('MetaLonDA')
library('Polychrome')
library("lsmeans")
library("cowplot")
library("reshape2")
library("nlme")
library("lme4")
library('ComplexHeatmap')
library('circlize')
library('gridtext')

